# Generated by Django 5.0.6 on 2024-07-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
